version: '3'

services:
    traefik:
        container_name: traefik
        image: "traefik:latest"
        command:
        - --entrypoints.web.address=:80
        - --entrypoints.websecure.address=:443
        - --providers.docker
        - --log.level=ERROR
        - --certificatesresolvers.leresolver.acme.httpchallenge=true
        - --certificatesresolvers.leresolver.acme.email=EMAIL
        - --certificatesresolvers.leresolver.acme.storage=./acme.json
        - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - "./acme.json:/acme.json"
        labels:
        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.http-catchall.entrypoints=web"
        - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    postgres:
        image: postgres:13.1
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - POSTGRES_PORT=${POSTGRES_PORT}
        volumes:
            - joplin_db:/var/lib/postgresql/data
    joplin:
        image: joplin/server:1.7.2
        depends_on:
            - db
        ports:
            - "22300:22300"
        restart: unless-stopped
        labels:
            - com.centurylinklabs.watchtower.enable=true
            - traefik.enable=true
            - traefik.http.routers.joplin.rule=Host(`joplin.boxingoctopus.io`)
            - traefik.http.routers.joplin.tls=true
            - traefik.http.routers.joplin.entrypoints=websecure
            - traefik.http.routers.joplin.service=joplin
            - traefik.http.routers.joplin.tls.certresolver=leresolver
            - traefik.http.services.joplin.loadbalancer.server.port=22300
            - traefik.http.middlewares.joplin.headers.SSLRedirect=true
            - traefik.http.middlewares.joplin.headers.STSSeconds=315360000
            - traefik.http.middlewares.joplin.headers.browserXSSFilter=true
            - traefik.http.middlewares.joplin.headers.contentTypeNosniff=true
            - traefik.http.middlewares.joplin.headers.forceSTSHeader=true
            - traefik.http.middlewares.joplin.headers.SSLHost=boxingoctopus.io
            - traefik.http.middlewares.joplin.headers.STSIncludeSubdomains=true
            - traefik.http.middlewares.joplin.headers.STSPreload=true
        environment:
            - APP_BASE_URL=${APP_BASE_URL}
            - APP_PORT=${APP_PORT}
            - DB_CLIENT=${DB_CLIENT}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
    joplin_db: